// Authored activity pockets. Their locations and pavement are shared by the
// render scene and terrain worker; scenery generation reserves these spaces.
export const livingSites = [
  {
    id: "conch-yard",
    area: "conch",
    kind: "yard",
    x: -462,
    z: 360,
    heading: 0,
    label: "CONCH POST",
  },
  {
    id: "conch-corner",
    area: "conch",
    kind: "stop",
    x: -516,
    z: 426,
    heading: 0.55,
    label: "CONCH STREET",
  },
  {
    id: "commons-market",
    area: "commons",
    kind: "market",
    x: -122,
    z: -43,
    heading: 0.25,
    label: "REEF MARKET",
  },
  {
    id: "commons-patio",
    area: "commons",
    kind: "patio",
    x: 24,
    z: -25,
    heading: -0.15,
  },
  {
    id: "commons-stop",
    area: "commons",
    kind: "stop",
    x: -105,
    z: 129,
    heading: 0.5,
    label: "RESTAURANT ROW",
  },
  {
    id: "fields-rest",
    area: "fields",
    kind: "patio",
    x: -646,
    z: -180,
    heading: 0.2,
  },
  {
    id: "lagoon-patio",
    area: "lagoon",
    kind: "patio",
    x: 461,
    z: 408,
    heading: -0.3,
  },
  {
    id: "lagoon-stall",
    area: "lagoon",
    kind: "market",
    x: 345,
    z: 440,
    heading: -0.1,
    label: "SHELL SNACKS",
  },
  {
    id: "lagoon-dock",
    area: "lagoon",
    kind: "dock",
    x: 535,
    z: 545,
    heading: 0.55,
    label: "LAGOON LANDING",
  },
  {
    id: "wreck-workshop",
    area: "wreck",
    kind: "workshop",
    x: 641,
    z: -191,
    heading: 0.55,
    label: "BOAT REPAIR",
  },
  {
    id: "wreck-dock",
    area: "wreck",
    kind: "dock",
    x: 757,
    z: -201,
    heading: 0.2,
    label: "COVE LANDING",
  },
  {
    id: "ridge-rest",
    area: "ridge",
    kind: "stop",
    x: 87,
    z: -692,
    heading: -0.2,
    label: "MOUNTAIN TRAIL",
  },
  {
    id: "palace-patio",
    area: "neptune",
    kind: "patio",
    x: -464,
    z: -585,
    heading: 0.2,
  },
  {
    id: "palace-stall",
    area: "neptune",
    kind: "market",
    x: -305,
    z: -600,
    heading: -0.2,
    label: "PEARL EXCHANGE",
  },
];
export function siteRadius(site) {
  return site.kind === "dock" ? 17 : 13;
}
